Revert "Remove delocate version constraint"
This reverts commit cb132bf3f5e3a0906e2977a32511daef0767b8d7.

NDI binaries still cause issues with delocate>0.10.7:

```
raise DelocationError(
  delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 11.0:
  /private/var/folders/ml/x_tvfgn50_s7p67dm1ypcqqm0000gn/T/tmp4mfqtxgo/wheel/cyndilib/wrapper/bin/libndi.dylib has a minimum target of 11.2
  /private/var/folders/ml/x_tvfgn50_s7p67dm1ypcqqm0000gn/T/tmp4mfqtxgo/wheel/cyndilib/.dylibs/libndi.dylib has a minimum target of 11.2
  Set the environment variable 'MACOSX_DEPLOYMENT_TARGET=11.2' to update minimum supported macOS for this wheel.
```